version: "3"

services:
  zookeeper:
    image: registry-vpc.cn-hangzhou.aliyuncs.com/idcos-common/zookeeper:3.6.3
    container_name: zookeeper
    network_mode: "host"
    volumes:
      - zookeeper_data:/bitnami
    environment:
      - TZ=Asia/Shanghai
      - ZOO_ENABLE_AUTH=yes
      - ZOO_SERVER_USERS=$ZOOKEEPER_USER
      - ZOO_SERVER_PASSWORDS=$ZOOKEEPER_PASSWORD
      - ZOO_CLIENT_USER=$ZOOKEEPER_USER
      - ZOO_CLIENT_PASSWORD=$ZOOKEEPER_PASSWORD
    restart: always

  kafka:
    image: registry-vpc.cn-hangzhou.aliyuncs.com/idcos-common/kafka:2.8.1
    container_name: kafka
    network_mode: "host"
    volumes:
      - kafka_data:/bitnami
    environment:
      - TZ=Asia/Shanghai
      - KAFKA_CFG_ZOOKEEPER_CONNECT=localhost:2181
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:SASL_PLAINTEXT,SASL_PLAINTEXT:SASL_PLAINTEXT,EXTERNAL_SASL_PLAINTEXT:SASL_PLAINTEXT,CLIENT:SASL_PLAINTEXT
      - KAFKA_CFG_LISTENERS=SASL_PLAINTEXT://0.0.0.0:9092,EXTERNAL_SASL_PLAINTEXT://0.0.0.0:39092
      - KAFKA_CFG_ADVERTISED_LISTENERS=SASL_PLAINTEXT://$HOST_IP:9092,EXTERNAL_SASL_PLAINTEXT://$INGRESS_HOST:39092
      - KAFKA_INTER_BROKER_USER=$KAFKA_USER
      - KAFKA_INTER_BROKER_PASSWORD=$KAFKA_PASSWORD
      - KAFKA_INTER_BROKER_LISTENER_NAME=SASL_PLAINTEXT
      - KAFKA_CFG_SASL_ENABLED_MECHANISMS=PLAIN
      - KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL=PLAIN
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_ALLOW_EVERYONE_IF_NO_ACL_FOUND=true
      - KAFKA_ZOOKEEPER_PROTOCOL=SASL_PLAINTEXT
      - KAFKA_ZOOKEEPER_USER=$ZOOKEEPER_USER
      - KAFKA_ZOOKEEPER_PASSWORD=$ZOOKEEPER_PASSWORD
      - KAFKA_CLIENT_USERS=$KAFKA_USER
      - KAFKA_CLIENT_PASSWORDS=$KAFKA_PASSWORD
      - KAFKA_CFG_MESSAGE_MAX_BYTES=104857600
      - KAFKA_CFG_MAX_REQUEST_SIZE=104857600
      - KAFKA_CFG_REPLICA_FETCH_MAX_BYTES=104857600
      - KAFKA_CFG_REPLICA_FETCH_WAIT_MAX_MS=2000
      - KAFKA_CFG_FETCH_MESSAGE_MAX_BYTES=104857600
      - KAFKA_CFG_MAX_POLL_RECORDS=20
      # - KAFKA_CFG_NUM_PARTITIONS=3
      # - KAFKA_CFG_GROUP_INITIAL_REBALANCE_DELAY_MS=3
      # - KAFKA_CFG_SESSION_TIMEOUT_MS=900000
      # - KAFKA_CFG_HEARTBEAT_INTERVAL_MS=200000
      # - KAFKA_CFG_MAX_POLL_INTERVAL_MS=900000
    restart: always
    depends_on:
      - zookeeper

  redis-node-0:
    image: registry-vpc.cn-hangzhou.aliyuncs.com/idcos-common/redis-cluster:6.0.16
    container_name: redis-node-0
    network_mode: "host"
    volumes:
      - redis_data-0:/bitnami/redis/data
    environment:
      - TZ=Asia/Shanghai
      - REDIS_PASSWORD=$REDIS_PASSWORD
      - REDIS_NODES=localhost:6379 localhost:6380 localhost:6381 localhost:6382 localhost:6383 localhost:6384
      - REDIS_PORT_NUMBER=6379
      - REDIS_CLUSTER_DYNAMIC_IPS=no
      - REDIS_CLUSTER_ANNOUNCE_IP=$HOST_IP
    restart: always

  redis-node-1:
    image: registry-vpc.cn-hangzhou.aliyuncs.com/idcos-common/redis-cluster:6.0.16
    container_name: redis-node-1
    network_mode: "host"
    volumes:
      - redis_data-1:/bitnami/redis/data
    environment:
      - TZ=Asia/Shanghai
      - REDIS_PASSWORD=$REDIS_PASSWORD
      - REDIS_NODES=localhost:6379 localhost:6380 localhost:6381 localhost:6382 localhost:6383 localhost:6384
      - REDIS_PORT_NUMBER=6380
      - REDIS_CLUSTER_DYNAMIC_IPS=no
      - REDIS_CLUSTER_ANNOUNCE_IP=$HOST_IP
    restart: always

  redis-node-2:
    image: registry-vpc.cn-hangzhou.aliyuncs.com/idcos-common/redis-cluster:6.0.16
    container_name: redis-node-2
    network_mode: "host"
    volumes:
      - redis_data-2:/bitnami/redis/data
    environment:
      - TZ=Asia/Shanghai
      - REDIS_PASSWORD=$REDIS_PASSWORD
      - REDIS_NODES=localhost:6379 localhost:6380 localhost:6381 localhost:6382 localhost:6383 localhost:6384
      - REDIS_PORT_NUMBER=6381
      - REDIS_CLUSTER_DYNAMIC_IPS=no
      - REDIS_CLUSTER_ANNOUNCE_IP=$HOST_IP
    restart: always

  redis-node-3:
    image: registry-vpc.cn-hangzhou.aliyuncs.com/idcos-common/redis-cluster:6.0.16
    container_name: redis-node-3
    network_mode: "host"
    volumes:
      - redis_data-3:/bitnami/redis/data
    environment:
      - TZ=Asia/Shanghai
      - REDIS_PASSWORD=$REDIS_PASSWORD
      - REDIS_NODES=localhost:6379 localhost:6380 localhost:6381 localhost:6382 localhost:6383 localhost:6384
      - REDIS_PORT_NUMBER=6382
      - REDIS_CLUSTER_DYNAMIC_IPS=no
      - REDIS_CLUSTER_ANNOUNCE_IP=$HOST_IP
    restart: always

  redis-node-4:
    image: registry-vpc.cn-hangzhou.aliyuncs.com/idcos-common/redis-cluster:6.0.16
    container_name: redis-node-4
    network_mode: "host"
    volumes:
      - redis_data-4:/bitnami/redis/data
    environment:
      - TZ=Asia/Shanghai
      - REDIS_PASSWORD=$REDIS_PASSWORD
      - REDIS_NODES=localhost:6379 localhost:6380 localhost:6381 localhost:6382 localhost:6383 localhost:6384
      - REDIS_PORT_NUMBER=6383
      - REDIS_CLUSTER_DYNAMIC_IPS=no
      - REDIS_CLUSTER_ANNOUNCE_IP=$HOST_IP
    restart: always

  redis-node-5:
    image: registry-vpc.cn-hangzhou.aliyuncs.com/idcos-common/redis-cluster:6.0.16
    container_name: redis-node-5
    network_mode: "host"
    volumes:
      - redis_data-5:/bitnami/redis/data
    depends_on:
      - redis-node-0
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
    environment:
      - TZ=Asia/Shanghai
      - REDIS_PASSWORD=$REDIS_PASSWORD
      - REDISCLI_AUTH=$REDIS_PASSWORD
      - REDIS_CLUSTER_REPLICAS=1
      - REDIS_NODES=localhost:6379 localhost:6380 localhost:6381 localhost:6382 localhost:6383 localhost:6384
      - REDIS_PORT_NUMBER=6384
      - REDIS_CLUSTER_DYNAMIC_IPS=no
      - REDIS_CLUSTER_ANNOUNCE_IP=$HOST_IP
      - REDIS_CLUSTER_CREATOR=yes
    restart: always

volumes:
  portainer:
    driver: local
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  redis_data-0:
    driver: local
  redis_data-1:
    driver: local
  redis_data-2:
    driver: local
  redis_data-3:
    driver: local
  redis_data-4:
    driver: local
  redis_data-5:
    driver: local
