---
version: 0.5

apply:
  steps:
    terraformApply:
      before:
        - |
          test -f ansible/export.yml || cd /cloudiac/workspace/code
          bash ansible/run.sh export.yml
          pwd
          sleep 10 &
          jobs -l
          wait

    ansiblePlay:
      after:
        - |
          test -f ansible/import.yml || cd /cloudiac/workspace/code
          bash ansible/run.sh import.yml
          pwd

destroy:
  steps:
    terraformDestroy:
      before:
        - |
          test -f ansible/export.yml || cd /cloudiac/workspace/code
          bash ansible/run.sh export.yml
          pwd
