---
version: 0.5

apply:
  steps:
    terraformApply:
      before:
        - |
          test -f ansible/export.yml || cd /cloudiac/workspace/code
          bash ansible/run.sh export.yml
          pwd
          sleep 30 &
          jobs -l
          wait
          terraform refresh --input=false --var-file=/cloudiac/workspace/_cloudiac.tfvars.json 
          terraform plan -input=false -out=_cloudiac.tfplan \
           -var-file=v1.3.tfvars -var-file=../../_cloudiac.tfvars.json \
          -destroy && \
          terraform show -no-color -json _cloudiac.tfplan >../../tfplan.json
    ansiblePlay:
      after:
        - |
          test -f ansible/import.yml || cd /cloudiac/workspace/code
          bash ansible/run.sh import.yml
          pwd

destroy:
  steps:
    terraformDestroy:
      before:
        - |
          test -f ansible/export.yml || cd /cloudiac/workspace/code
          bash ansible/run.sh export.yml
          pwd
