---
version: 0.5

apply:
  steps:
    terraformApply:
      before:
        - |
          test -f ansible/export.yml || cd /cloudiac/workspace/code
          bash ansible/run.sh export.yml
          pwd
          sleep 60 &
          jobs -l
          wait
          terraform refresh --input=true --var-file=/cloudiac/workspace/_cloudiac.tfvars.json 

    ansiblePlay:
      after:
        - |
          test -f ansible/import.yml || cd /cloudiac/workspace/code
          bash ansible/run.sh import.yml
          pwd

destroy:
  steps:
    terraformDestroy:
      before:
        - |
          test -f ansible/export.yml || cd /cloudiac/workspace/code
          bash ansible/run.sh export.yml
          pwd
